### ISSUE TITLE
User can look up three locations they want to add to a route

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#1]
## 💰 Motivation

Users will want to create a walking route and include three different locations to visit.

## 📐 Plan

Create a form that allows users to input three locations to be added to the route. Enable autocomplete feature so that users can see and select suggestions for the location they are entering. Add this feature to the navigation menu so that users can easily access it.

## 🖼️ Wireframe

<img width="790" alt="User can look up three locations" src="https://user-images.githubusercontent.com/65578254/113644101-c7d6a500-9638-11eb-859f-4d3cfb0737cf.png">

![image](https://user-images.githubusercontent.com/65578254/113656154-1ba0b880-9650-11eb-9207-b1a5c0bb6c03.png)

<img width="1440" alt="User can look up three locations (1)" src="https://user-images.githubusercontent.com/65578254/113656201-35da9680-9650-11eb-855d-0d4edfb5a7ca.png">

## ✅ Task List

- [x] Create a `map-route.jsx` within the `pages` directory of the `client` directory
- [x] Create a `location-form.jsx` within the `components` directory of the `client` directory
- [x] Add constructor, render, handleChange, and handleSubmit methods to the `LocationForm` class
- [x] Add a React form element with three text inputs for the locations, labels for the text inputs, and a "Go" button
- [x] Add styling for a "row" class to `styles.css` that implements Flexbox
- [x] Edit the styling so that the form looks like the wireframe
- [x] Implement the Google Map API autocomplete feature for each text input
- [x] Add an `onClick` prop for the "Go" button
- [x] Add media breakpoints to ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all styling that had no effect or was otherwise unnecessary
- [x] Fix all errors
