### ISSUE TITLE
User can view a leaderboard of distance walked among their friends in the past week

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#10]
## 💰 Motivation

Users will want to see how much their friends have walked in the past week and compare it to how much they have walked.

## 📐 Plan

Create a list of friends (including the user) ranked according to the distance walked in the past week. Include each walker's rank, name, and distance walked, as well as the dates of the current week.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/113765878-ad043f00-96d1-11eb-975a-cc31f35e6ef2.png)
<img width="1439" alt="User can view leaderboard of distance walked among their friends in the past week" src="https://user-images.githubusercontent.com/65578254/113765799-96f67e80-96d1-11eb-93c4-568e67bf9b8a.png">

## ✅ Task List

- [x] Create a `leaderboard.jsx` page and link it to the app via hash routing and the navbar links
- [x] Set up the page layout using dummy data so that the page looks like the wireframe
- [x] Update the `users` table in the database to include the dummy data for the distance walked by the user that week
- [x] Write a `fetch` request to get the user's friend data from the server
- [x] Update `index.js` to determine how the server will respond to the `GET` request
- [x] Ensure that the data from the database can be displayed on the leaderboard
