### ISSUE TITLE
User can view the mapped route

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#2]
## 💰 Motivation

Users will want to view the walking route they are creating on a map.

## 📐 Plan

Add a map that displays the directions going to the three locations they entered. Enable draggable directions so that users can modify the highlighted route by dragging it on the map.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/113755965-c0a9a880-96c5-11eb-9973-a3df26556c00.png)
![image](https://user-images.githubusercontent.com/65578254/113756025-cc956a80-96c5-11eb-81c4-86084793a017.png)
![image](https://user-images.githubusercontent.com/65578254/113756076-da4af000-96c5-11eb-85ec-2d866d63a227.png)

## ✅ Task List

- [x] Within `map-route.jsx`, create a `Map` component that returns a `div` containing a Google Map
- [x] Ensure that the route begins at the start location, passes through the two stops, and ends at the start location
- [x] Enable draggable directions on the mapped route
- [x] Add hash routing to enable toggling between the form and the map
- [x] Add the user's locations as markers on the map
- [x] Ensure that the map looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Enable the map to appear when the user clicks the submit button on the location form
- [x] Fix all errors
