### ISSUE TITLE
User can log in to their account

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#21]
## 💰 Motivation

Users will want to be able to log in to their account or register for a new account.

## 📐 Plan

Create a login form that also provides the user the option to register for an account

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/115137917-b947a080-9fdd-11eb-9b74-e3b0fab85ab2.png)
![image](https://user-images.githubusercontent.com/65578254/115137956-fdd33c00-9fdd-11eb-9810-a2cba172f8bf.png)

## ✅ Task List

- [x] Create a new page for user login
- [x] Link the form to the app and save the user in the state
- [x] Set up the page so that it looks like the wireframe
- [x] Make sure the form looks nice on both mobile and desktop views
- [x] Write `handleChange` and `handleSubmit` methods in `auth-form.jsx` to handle user inputs
- [x] Update `users` table in database to store each `username` and `hashedPassword`
- [x] Update `index.js` to determine how the server will respond to sign-up requests
- [x] Update `index.js` to determine how the server will respond to log-in requests
- [x] Add a Sign Out button in mobile view
