### ISSUE TITLE
User can add a friend

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#26]
## 💰 Motivation

Users will want to add a friend on the app.

## 📐 Plan

Create a form that allows the user to send a request to add a friend on the app.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/115968986-76ab2a00-a4ef-11eb-8cd5-3465fbd109a1.png)

## ✅ Task List

- [x] Add a table in the database for friend requests
- [x] Create a page for Add a Friend and link it to the app via hash routing
- [x] Set up the page layout so that front-end looks like the wireframe
- [x] Write the fetch request on the back-end to compare the user's input with the usernames in the database
- [x] Display an error if there is no matching username in the database
