### ISSUE TITLE
User can accept a friend request

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#28]
Users will want to accept friend requests from other users.

## 📐 Plan

Create a view that enables the user to view friend requests and either accept or delete them.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/115975147-1af49700-a517-11eb-93fe-df0ce37b9fd0.png)

## ✅ Task List

- [x] Create a page for Friend Requests and link it to the app via hash routing
- [x] Set up the page layout so that front-end looks like the wireframe
- [x] Write fetch requests for the front and back-end for deleting a friend request
- [x] Write fetch requests for the front and back-end for accepting a friend request
