### ISSUE TITLE
User can view the route details

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#3]
## 💰 Motivation

Users will want to see the total distance and walking time of the route, as well as the directions.

## 📐 Plan

Display the distance, time, and directions on the route details page alongside the mapped route. Add a button so that user can add the route to their saved routes.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/114249017-32942300-994e-11eb-984d-e0b8c60d9275.png)
![image](https://user-images.githubusercontent.com/65578254/114248873-c4e7f700-994d-11eb-8da9-0f8cea3852fe.png)

## ✅ Task List

- [x] Display the textual display of directions from the Google Maps API using sample data
- [x] Get the total distance and time for the trip to display along with the directions
- [x] Edit the styling so that the form looks like the wireframe
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all styling that had no effect or was otherwise unnecessary
- [x] Fix all errors
