### ISSUE TITLE
User can view a list of saved routes

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#4]
## 💰 Motivation

Users will want to see a list of routes they have saved. Users will want to see the route details upon clicking on the list item.

## 📐 Plan

Create a list view for saved routes, with each list item indicating the start location, two stops, distance, and walking time. Enable users to see a modified view of the route details by clicking on the route, which includes the date last walked, date planned for the next walk, and a list of friends the route has been shared with. The route details page also includes options to un-save, share, edit or view directions for the route. Add this feature to the navigation menu so that users can easily access it.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/113758765-2481a080-96c9-11eb-870e-5a4ac8382f07.png)
![image](https://user-images.githubusercontent.com/65578254/113760382-01f08700-96cb-11eb-9773-972396ca8225.png)
![image](https://user-images.githubusercontent.com/65578254/113761066-e0dc6600-96cb-11eb-8ee4-c36f4aa9a895.png)
![image](https://user-images.githubusercontent.com/65578254/113758556-e1273200-96c8-11eb-928b-0bf46264c55c.png)
![image](https://user-images.githubusercontent.com/65578254/113760449-19c80b00-96cb-11eb-8a40-90aafe4c3904.png)
![image](https://user-images.githubusercontent.com/65578254/113761178-ff426180-96cb-11eb-81bf-a8d256beda5a.png)

## ✅ Task List

- [x] Add a Save button to the route details page with an icon that changes on click
- [x] Create a `saved-routes.jsx` file for the saved routes page and add hash routing to enable navigating to it
- [x] Use example location information to set up the list of saved routes so that it resembles the wireframe
- [x] Set up the database to store the information for the saved routes
- [x] Write a `fetch` request in `saved-routes.jsx` to request the saved routes from the server
- [x] Update `index.js` to determine how the server will respond to the `GET` request
- [x] Connect the database so that the routes in the database are displayed on the list of saved routes
- [x] Make sure that if there are no saved routes in the database, the user can see a message indicating that
- [x] Modify the route details page to optionally show the Last walked date, Next walk date, and Shared with information
- [x] Write a `fetch` request in `saved-routes.jsx` to request a single saved route from the server
- [x] Update `index.js` to determine how the server will respond to the `GET` request for that route
- [x] Ensure that the user can view the modified route details page upon clicking on a route in the list
- [x] Set up the Save button so that it saves the selected route to the database
- [x] Write a `fetch` request in `saved-routes.jsx` to save the selected route
- [x] Update `index.js` to determine how the server will respond to the `POST` request for that route
- [x] Write a `fetch` request in `saved-routes.jsx` to unsave the selected route
- [x] Update `index.js` to determine how the server will respond to the `DELETE` request for that route
- [x] For mobile view, create the navbar footer and add the logos from Font Awesome
- [x] For desktop view, create an app drawer menu and add the navigation options
