### ISSUE TITLE
User can share a walking route with friends

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#5]
## 💰 Motivation

Users will want to share a saved route with their friends to invite them to walk together.

## 📐 Plan

Create a form that allows users to select which friends they want to share a route with. Users will have the option to include a date if planning a future walk.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/113759674-34e64b00-96ca-11eb-915b-05e98dd0c585.png)
![image](https://user-images.githubusercontent.com/65578254/113759729-4596c100-96ca-11eb-97a9-e87cb1141b85.png)

## ✅ Task List
- [x] Add a table to the database to store the user's friends
- [x] Create a new page `share.jsx` and connect it to the app via hash routing
- [x] Set up the layout of the page using example data from the wireframe
- [x] Link the pages so that clicking the Share button on the Route Details page navigates the user to select friends
- [x] Make sure that clicking the Share button on the Friends page navigates the user back to Route Details
- [x] Write a `fetch` request in `share.jsx` to obtain a list of the user's friends from the database
- [x] Update `index.js` to determine how the server will respond to the GET request
- [x] Ensure that the friend data from the database is reflected on the page
- [x] Write a `fetch` request in `share.jsx` to send the selected friends to the database
- [x] Update `index.js` to determine how the server will respond to the PATCH request
