### ISSUE TITLE
User can add a date and time to a saved route

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#6]
## 💰 Motivation

Users will want to either add a past date to the saved route to record that it has been completed or add a future date to the route to mark that it is planned.

## 📐 Plan

Create a form that allows users to select a date and time.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/113761699-9c04ff00-96cc-11eb-942b-54a67c4b4747.png)
![image](https://user-images.githubusercontent.com/65578254/113761744-aa531b00-96cc-11eb-8435-199e2d268a9b.png)

## ✅ Task List

- [x] Create a new component `add-date.jsx`
- [x] Create the modal and set up the layout to look like the wireframe
- [x] Add `handleChange` and `handleSubmit` methods to update the state with the selected date
- [x] Make sure that the Add Date button from the Share page opens the modal
- [x] Write a `fetch` request to save the date for the route to the database
- [x] Update `index.js` to determine how the server will respond to the PATCH request
- [x] Make sure that clicking Save adds the date to the Last Walked or Next Walk list on the Route Details page
