### ISSUE TITLE
User can delete a date from a saved route

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#7]
## 💰 Motivation

Users will want to remove a recorded date from a saved route in case it was added by mistake or needs to be adjusted for some reason.

## 📐 Plan

Create an edit form where users will have the option to remove a "Last walked" or "Next walk" date from a saved route. Users will need to double click to confirm that they are deleting the date, then they will be provided the option to add a new date.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/65578254/113762951-f9e61680-96cd-11eb-92f5-ca8297440366.png)
![image](https://user-images.githubusercontent.com/65578254/113763005-09655f80-96ce-11eb-8b1d-84c6bce1420b.png)
![image](https://user-images.githubusercontent.com/65578254/113763138-2ef26900-96ce-11eb-8696-f8288a617d31.png)
![image](https://user-images.githubusercontent.com/65578254/113763228-4e899180-96ce-11eb-9ba6-16f17a08e8ee.png)
![image](https://user-images.githubusercontent.com/65578254/113763293-63662500-96ce-11eb-92b4-9e7293130678.png)
![image](https://user-images.githubusercontent.com/65578254/113763351-7547c800-96ce-11eb-9a44-1ece11637f68.png)

## ✅ Task List

- [x] Created an `edit-route.jsx` page and link it to the app via hash routing and the Edit button on the Route Details page
- [x] Add logos from Font Awesome and set up the page to look like the wireframe using example information
- [x] Set up the minus icons to change into trash can icons on click
- [x] Ensure that clicking the trash icons will send a delete request to the database
- [x] Set up the existing date to change into the Add Date button upon successful deletion
- [x] Add actual dates from the database for Last Walked and Next Walk
- [x] Make sure that clicking the Done button will navigate the user back to the Route Details page

**Comment by angelsleung** [comment]
![issue-7-delete-datev2](https://user-images.githubusercontent.com/65578254/114938357-e0db1500-9df3-11eb-8765-eaa1425dc3ea.gif)
