### ISSUE TITLE
User can delete a route from their saved routes

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#8]
## 💰 Motivation

Users will want to have the ability to remove a saved route.

## 📐 Plan

On the route's edit page, add an option to delete the route. Allow users to double click to confirm that they would like to delete the route, then navigate to the list of saved routes.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/113764081-58f85b00-96cf-11eb-88c7-1181d6de2d98.png)
![image](https://user-images.githubusercontent.com/65578254/113760382-01f08700-96cb-11eb-9773-972396ca8225.png)
![image](https://user-images.githubusercontent.com/65578254/113764125-69103a80-96cf-11eb-898f-3a32835532c0.png)
![image](https://user-images.githubusercontent.com/65578254/113760449-19c80b00-96cb-11eb-8a40-90aafe4c3904.png)

## ✅ Task List

- [x] Enable the trash can icon to appear when Delete Route is clicked
- [x] On the second click, send a `DELETE` `fetch` request to the server
- [x] Ensure that the user is routed back to the saved routes page upon successful deletion
