### ISSUE TITLE
User can view a list of routes that friends have shared with them

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/walk-with-friends#9]
## 💰 Motivation

Users will want to view the walking routes that friends have shared with them, including the planned date/time, distance, and walking time.

## 📐 Plan

Create a list view that displays the routes that have been shared with the user. Clicking on a route will lead users to the route details page, which includes the directions as well as an option to save the route as a favorite. Add this feature to the navigation menu so that users can easily access it.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/113764758-3f0b4800-96d0-11eb-9245-bf5b4e60a2bd.png)
![image](https://user-images.githubusercontent.com/65578254/113764645-1a16d500-96d0-11eb-8092-d6352a8bfd1a.png)
![image](https://user-images.githubusercontent.com/65578254/113764402-c0160f80-96cf-11eb-8fb9-005f940294db.png)
![image](https://user-images.githubusercontent.com/65578254/113764823-55b19f00-96d0-11eb-83b2-d8a7c3d97154.png)

## ✅ Task List

- [x] Create a `friends-routes.jsx` page and link it to the app via hash routing and the navbars
- [x] Structure the app to look like the wireframe, using dummy data
- [x] Create a new table in the database to store friends' routes and insert dummy data for testing purposes
- [x] Write a `fetch` `GET` request to obtain friends' routes data
- [x] Update `index.js` to determine how the server will respond to the request
- [x] Ensure that the data from the database is being displayed in the friends' routes list
- [x] Make sure that clicking on the route list item navigates the user to the route details and directions
